# Generated by Django 3.1.4 on 2021-01-25 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(blank=True, max_length=70, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_address_line1', models.CharField(blank=True, max_length=60, null=True)),
                ('user_address_line2', models.CharField(blank=True, max_length=60, null=True)),
                ('user_town_or_city', models.CharField(blank=True, max_length=50, null=True)),
                ('user_county', models.CharField(blank=True, max_length=50, null=True)),
                ('user_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('user_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
