# Generated by Django 3.1.4 on 2021-02-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_full_name',
        ),
    ]
