# Generated by Django 3.1.4 on 2021-02-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address_line',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.CharField(max_length=240),
        ),
    ]
