# Generated by Django 3.1.4 on 2021-02-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210212_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
