# Generated by Django 3.1.4 on 2020-12-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201216_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image01',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
