# Generated by Django 3.1.4 on 2020-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201217_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_comment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
