# Generated by Django 3.1.4 on 2020-12-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201218_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image01',
            new_name='image01',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image02',
            new_name='image02',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url01',
            new_name='img_url01',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url02',
            new_name='img_url02',
        ),
    ]
