# Generated by Django 3.1.4 on 2021-01-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210110_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frame_img',
        ),
    ]
