# Generated by Django 3.1.4 on 2021-01-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_frame_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('BLACK', 'BLACK')], default='RED', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.CharField(choices=[('ALLOY', 'ALLOY'), ('CARBON', 'CARBON')], default='ALLOY', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=7),
        ),
    ]
